argocd-example-app:
  ingress:
    public: true
    host: argocd-example-a.ocp.cloudscale.puzzle.ch
  deployment:
    image: registry.puzzle.ch/cicd/argocd-example-app
    replicas: 1
    tag: latest
  theme: squid
  stage: PROD