apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exapp
spec:
  generators:
    - list:
        elements:
          - customer: a
            stage: prod
            clusterName: ocp4-cloudscale-production
          # - customer: B
          #   stage: prod
          #   clusterName: ocp4-cloudscale-production
          # - customer: A
          #   stage: staging
          #   clusterName:  ocp4-cloudscale-staging
          # - customer: B
          #   stage: staging
          #   clusterName:  ocp4-cloudscale-staging
  template:
    metadata:
      name: exapp-{{stage}}-{{customer}}
    spec:
      source:
        repoURL: https://github.com/schlapzz/argocd-ops-example.git
        targetRevision: propagation
        path: subchart
        helm:
          valueFiles:
          - common/values.yaml
          - variants/customer-{{customer}}/values.yaml
          - variants/customer-{{customer}}/values.yaml
          - envs/{{stage}}-{{customer}}/values.yaml
          - envs/{{stage}}-{{customer}}/version.yaml
      project: pitc-apps
      destination:
        name: ocp4-cloudscale-production
        namespace: pitc-cicd-argocd-example-{{stage}}-{{customer}}
