apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-example-app
  namespace: openshift-gitops
spec:
  destination:
    name: ocp4-cloudscale-production
    namespace: pitc-cicd-argocd-example-app
  project: pitc-apps
  source:
    helm:
      valueFiles:
        - common/values.yaml
        - variants/customer-a/values.yaml
        - variants/prod/values.yaml
        - envs/prod-a/values.yaml
        - envs/prod-a/version.yaml
    path: subchart
    repoURL: 'https://github.com/schlapzz/argocd-ops-example.git'
    targetRevision: propagation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



      